FROM python:3.11-slim

WORKDIR /app

# Install Poetry
RUN pip install --no-cache-dir poetry

# Copy home dashboard app
COPY home_dashboard /app/home_dashboard
COPY playlists.json /app/playlists.json

# Install dependencies
WORKDIR /app/home_dashboard
RUN poetry install --no-dev

# Expose port
EXPOSE 8000

# Run FastAPI
CMD ["poetry", "run", "uvicorn", "home_dashboard.main:app", "--host", "0.0.0.0", "--port", "8000"]
